### ISSUE TITLE
No property found error

### ISSUE THREAD

**Issue by muhammetsahin** [sthewissen/Xamarin.Forms.StateSquid#1]
Hi,

Congrats your project. It is really really awesome.

But I added into my project i got and error.

" No property, bindable property, or event found for 'LoadingTemplate', or mismatching type between value and property."

![image](https://user-images.githubusercontent.com/2045788/62720818-829d4280-ba13-11e9-8d45-1ba339a79160.png)

Xamarin forms version: 4.1.0.673156
Xamarin.Forms.StateSquid version: 1.0.2-beta
Visual Studio 2019 pro 16.2.1

Do you have any idea?

Thanks.

**Comment by muhammetsahin** [comment]
Ok got it i guess i missed that.

`   <state:StateLayout.LoadingTemplate>
          <state:StateDataTemplate>
            <DataTemplate>
              <StackLayout HorizontalOptions="CenterAndExpand" VerticalOptions="CenterAndExpand">
                <ActivityIndicator IsRunning="{Binding MainState, Converter={StaticResource StateToBooleanConverter}, ConverterParameter={x:Static state:State.Loading}}" Color="#1abc9c" />
                <Label HorizontalOptions="Center" Text="Loading..." />
              </StackLayout>
            </DataTemplate>
          </state:StateDataTemplate>
        </state:StateLayout.LoadingTemplate>`

**Comment by sthewissen** [comment]
Yeah, this is one of the things I still want to fix. Directly inheriting from DataTemplate seems to be impossible, so I need to wrap into a custom object which means you have to write that somewhat stupid XAML. I hope to find a fix before going out of beta.
