### ISSUE TITLE
Unable to make it work. ¿What do I missing?

### ISSUE THREAD

**Issue by georgeemr** [sthewissen/Xamarin.Forms.StateSquid#10]
I'm making this on one page but looks like it's not working. I'm using Xamarin Forms 4.3.

![image](https://user-images.githubusercontent.com/3822009/67455158-fe0d9980-f5e9-11e9-8fb7-1dfc14278f8c.png)

**Comment by georgeemr** [comment]
I'm using the same view, but the State is not doing any changes. :(

![image](https://user-images.githubusercontent.com/3822009/67497307-08a44f00-f63b-11e9-8757-71017c8d3e82.png)

**Comment by sthewissen** [comment]
Do you have your MVVM set up in such a way that `INotifyPropertyChanged` is implemented for the `SkeletonState` property?

**Comment by georgeemr** [comment]
You are correct. Thanks
