### ISSUE TITLE
Statesquid crashing on latest stable  XF version.

### ISSUE THREAD

**Issue by Pinox** [sthewissen/Xamarin.Forms.StateSquid#13]
Hi,

Just to let you know that there seems to be issues with statesquid when updating the sample project to latest stable nuget versions.

1) Repeater template no longer works.

2) when you press "cycle all states" and while running press "show full screen loader" then you are greeted with :

![statesquid](https://user-images.githubusercontent.com/5297255/71149092-3a4e2680-2236-11ea-8f85-fff595223191.PNG)

Plse find link below to repo that results in the issues above:

https://drive.google.com/open?id=1A2_jJAHIxvpmqEaw3t87ZQWXr8RYpd7P

**Comment by sthewissen** [comment]
I cannot reproduce the first one, but I can repro the second. However, not sure if its something in StateSquid or Xamarin.Forms itself. The error is mentioned on their Github a few times, with it being referenced just a few weeks ago in https://github.com/xamarin/Xamarin.Forms/issues/2584
